[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libs={path = "../libs"}

log = "0.4.21"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21.0"